name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "21 3 * * 3"
  push:
    branches: [main]

permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    if: github.event.repository.default_branch == github.ref_name
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Retain SARIF evidence
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: scorecard-results
          path: results.sarif
          retention-days: 5

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@4187e74d05793876e9989daffde9c3e66b4acd07 # v3
        with:
          sarif_file: results.sarif
